### ISSUE TITLE
How can I change the background and logo design of my site?

### ISSUE THREAD

**Issue by creator-yoshiki** [The-Stripes-NFT/nft-minting-app#1]
Thank you very much for making such a wonderful tool. I really think you are a genius.
I would like to change the logo and background design of the minting site if possible, but I don't know how.
If you don't mind, please let me know.

**Comment by sultan-710** [comment]
just by replacing your own logo and background in your main nft-minting-app-main folder. :>

**Comment by martinnaj** [comment]
@alisolanki Close this please.
