### ISSUE TITLE
npm run start error

### ISSUE THREAD

**Issue by RippedFish** [The-Stripes-NFT/nft-minting-app#14]
Getting this error: Failed at the the_stripes_nft_dapp@1.0.0 start script 'react-scripts start'.

**Comment by alisolanki** [comment]
Try running `npm install` first

**Comment by RippedFish** [comment]
Yeah I did that. I found a fix where rewrite the read script. Sorry I'm
away from my comp..

**Comment by matteotrogu** [comment]
@RippedFish i have the same problem, how did you do it?
