### ISSUE TITLE
when i put npm run start, to start on localhost it tells me

### ISSUE THREAD

**Issue by matteotrogu** [The-Stripes-NFT/nft-minting-app#16]
npm ERR! Missing script: "start"
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\filip\AppData\Local\npm-cache\_logs\2022-03-03T14_44_18_950Z-debug-0.log

**Comment by martinnaj** [comment]
Have you followed the other steps?

**Comment by martinnaj** [comment]
Try running npm install again.

**Comment by matteotrogu** [comment]
@martinnaj I have already tried it always writes me like this

**Comment by matteotrogu** [comment]
@martinnaj 
 tells me missing script start

**Comment by FrancoisCoding** [comment]
> @martinnaj tells me missing script start

you never installed the packages
npm install

**Comment by alisolanki** [comment]
Try running `npm install` first

**Comment by matteotrogu** [comment]
@alisolanki still??? I told you it doesn't work,I've already tried

**Comment by matteotrogu** [comment]
@alisolanki retry the question

**Comment by martinnaj** [comment]
Try reinstalling the repo, there seem to be missing files.
