### ISSUE TITLE
Mint is 'stuck'

### ISSUE THREAD

**Issue by reswobzil** [The-Stripes-NFT/nft-minting-app#17]
I am having issues with the dapp.  My site is www.wellnessinitiative.io.
When I try and test whether or not I can mint an NFT, it lets me connect to my wallet, but when I click buy, it will stay stuck on the screenshot I have below.  Please help!
![image](https://user-images.githubusercontent.com/97857470/156666735-8a18b9cd-10aa-49d9-85bc-e4ca0161344c.png)

**Comment by alisolanki** [comment]
Have you gotten any transaction confirmation on your metamask wallet? Usually it is because the contract is not properly connected with the DApp

**Comment by reswobzil** [comment]
> Have you gotten any transaction confirmation on your metamask wallet? Usually it is because the contract is not properly connected with the DApp

I have not.  I agree that might be the issue but not sure how to troubleshoot.  Any help would be greatly appreciated.

**Comment by ultimateglue** [comment]
need to see what error outputs on the developer console

**Comment by reswobzil** [comment]
I've resolved the issue. Thank you!

**Comment by supraditya** [comment]
@reswobzil If you don't mind me asking, could you please tell us what fixed the issue for you? It seems many devs are having the same problem cropping up on their websites, thanks!

**Comment by supraditya** [comment]
I see. I've debugged everything except the contract's ABI, hopefully fixing that would get the site to work. Thanks!
