### ISSUE TITLE
Change from Matic to Eth

### ISSUE THREAD

**Issue by faustoandreabellucci** [The-Stripes-NFT/nft-minting-app#36]
Is possible change the payment from matic to eth ?

**Comment by 0xZeroBaby** [comment]
In config.json at line 5,6 and 7  change "Polygon" , "Matic"  and ID to mainnet

**Comment by faustoandreabellucci** [comment]
ok thanks. Can you tell me how I can allow a customer to access even from a mobile phone?

**Comment by 0xZeroBaby** [comment]
Are you italian? By the way, they need to access via Metamask App on mobile via browser inside the app

**Comment by faustoandreabellucci** [comment]
Yes I'm :D . when I click on Connect he tells me to install Metamask but I already have the app

**Comment by 0xZeroBaby** [comment]
Stai entrando tramite il browser dell'app di metamask?

**Comment by faustoandreabellucci** [comment]
lol. tramite il broswer premo connect e mi dice installa metamask ma sul telefono ho l'app non metamask installato sul browser

**Comment by faustoandreabellucci** [comment]
se poi vado sul browser ad installare Metamask giustamente mi fa entrare nell'app perchè l'installazione su mobile si tratta di scaricare l'app

**Comment by 0xZeroBaby** [comment]
Si, io intendo che nell'App Metamask, cè un browser dedicato proprio per poter usare il wallet da mobile
![Uploading 1.png…]()

**Comment by faustoandreabellucci** [comment]
Se vai ad es. su seabums.io e vuoi comprare un NFT dal telefono ti fa connettere con MetaMask e te lo fa mintare. Invece con il vostro pulsante no. Abbastanza problematico dato che il 99% delle persone sta dal telefono

**Comment by 0xZeroBaby** [comment]
Trovato?

**Comment by faustoandreabellucci** [comment]
Si se copio il link della D'apparato e lo incollo sul Browser di MetaMask nella app mi fa connettere grazie. Per caso c'è un modo per farlo connettere automaticamente senza copiare il link e incollarlo nel browser di MetaMask ? Giusto per rendere l'esperienza del compratore più semplice

**Comment by 0xZeroBaby** [comment]
No purtroppo da mobile l'unica opzione è usare il browser di Metamask.
Comunque qeust'app non è mia, ma sono un fruitore, sono un dev di progetti NFT ho fatto parecchie cose, sentiamoci se hai bisogno

**Comment by faustoandreabellucci** [comment]
A ok grazie sei stato gentilissimo. So che è possibile perché da altre collezioni cliccando il pulsante di mint il telefono riesce da solo a raggiungere MetaMask senza copiare ed incollare nel browser dedicato. Comunque già così mi hai aiutato tantissimo grazie davvero

**Comment by 0xZeroBaby** [comment]
Di nulla! Comunque questo è come ho reso il sito di questa repo https://thebestknives.xyz

**Comment by faustoandreabellucci** [comment]
Bellissimo,io tengo un poco di più alla funzionalità,se trovi il modo per fare come fa questa collezione pago volentieri.https://user-images.githubusercontent.com/93926793/211747811-76f57e58-a8aa-49dd-830c-28babfc02b20.MOV

**Comment by 0xZeroBaby** [comment]
Ti aggiorno

**Comment by faustoandreabellucci** [comment]
Ok ti ringrazio
